"""Pierre Git Storage SDK for Python.

A Python SDK for interacting with Pierre's git storage system.
"""

from pierre_storage.auth import encode_refs_claim, generate_jwt
from pierre_storage.client import GitStorage, create_client
from pierre_storage.errors import ApiError, RefUpdateError
from pierre_storage.types import (
    OP_NO_FORCE_PUSH,
    OP_NO_PUSH,
    BaseRepo,
    BlameLine,
    BlameResult,
    BranchInfo,
    CommitInfo,
    CommitMetadata,
    CommitResult,
    CommitSignature,
    CreateBranchResult,
    CreateTagResult,
    DeleteBranchResult,
    DeleteRepoResult,
    DeleteTagResult,
    DiffFileState,
    DiffStats,
    FileDiff,
    FileWithMetadata,
    FilteredFile,
    GetBranchDiffResult,
    GetCommitDiffResult,
    GetCommitResult,
    GitStorageOptions,
    GrepFileMatch,
    GrepLine,
    GrepResult,
    ListBranchesResult,
    ListCommitsResult,
    ListFilesResult,
    ListFilesWithMetadataResult,
    ListReposResult,
    ListTagsResult,
    NoteReadResult,
    NoteWriteResult,
    Op,
    Ops,
    RefPolicy,
    Refs,
    RefUpdate,
    Repo,
    RepoInfo,
    RestoreCommitResult,
    TagInfo,
)
from pierre_storage.version import PACKAGE_VERSION
from pierre_storage.webhook import (
    WebhookPushEvent,
    parse_signature_header,
    validate_webhook,
    validate_webhook_signature,
)

__version__ = PACKAGE_VERSION

__all__ = [
    # Main client
    "GitStorage",
    "create_client",
    # Auth
    "encode_refs_claim",
    "generate_jwt",
    # Errors
    "ApiError",
    "RefUpdateError",
    # Types
    "BaseRepo",
    "BlameLine",
    "BlameResult",
    "BranchInfo",
    "CommitMetadata",
    "CreateBranchResult",
    "CreateTagResult",
    "CommitInfo",
    "CommitResult",
    "CommitSignature",
    "DeleteBranchResult",
    "DeleteRepoResult",
    "DeleteTagResult",
    "DiffFileState",
    "DiffStats",
    "FileWithMetadata",
    "FileDiff",
    "FilteredFile",
    "GetBranchDiffResult",
    "GetCommitDiffResult",
    "GetCommitResult",
    "GrepFileMatch",
    "GrepLine",
    "GrepResult",
    "GitStorageOptions",
    "Op",
    "OP_NO_FORCE_PUSH",
    "OP_NO_PUSH",
    "Ops",
    "RefPolicy",
    "Refs",
    "ListBranchesResult",
    "ListCommitsResult",
    "ListFilesResult",
    "ListFilesWithMetadataResult",
    "ListReposResult",
    "ListTagsResult",
    "NoteReadResult",
    "NoteWriteResult",
    "RefUpdate",
    "RepoInfo",
    "Repo",
    "RestoreCommitResult",
    "TagInfo",
    # Webhook
    "WebhookPushEvent",
    "parse_signature_header",
    "validate_webhook",
    "validate_webhook_signature",
]
