name: Publish SDK beta

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      channel: beta
    secrets: inherit
